#!/bin/bash

#python run_scripts/sim_to_fit/run_sim_to_fit.py --dbName ddf_accordion_v5.0.0_10yrs --dbDir ../DB_Files --dbExtens npy --OutputSimu_save 1 --OutputSimu_throwafterdump 0 --SN_x1_type random --SN_color_type random --SN_z_type random --SN_z_min 0.5 --SN_z_max 1.11 --SN_sigmaInt 0.0 --SN_z_rate Hounsell --SN_daymax_type random --Simulator_model salt3 --Simulator_version 2.0 --Fitter_model salt3 --Fitter_version 2.0 --MultiprocessingSimu_nproc 8 --MultiprocessingFit_nproc 8 --nproc_pixels 8 --nproc 1 --SN_NSNfactor 30 --fit_selected 0 --ebvofMW_pixel 0.0 --OutputSimu_directory ../test_ddf --OutputFit_directory ../test_ddf --fieldType DD --nside 128 --Fitter_parnames t0,x1,c,x0  --InstrumentSimu_telescope_tag 1.9 --InstrumentFit_telescope_tag 1.9 --Fitter_sigmaz 1e-05 --SN_smearFlux 1 --lookup_ddf input/simulation/lookup_ddf.csv --saturation_effect 0 --saturation_psf single_gauss --saturation_ccdfullwell 120000.0 --SN_z_sigmaz 1e-05 --fit_remove_sat 0 --SN_NSNabsolute 200 --LCSelection_snrmin 1.0 --code new --Pixelisation_nside 128 --fieldName EDFS_b --ProductionIDSimu SN_test_COSMOS --Observations_season 2 --InstrumentSimu_atmosType=const --Observations_coadd=1 --fit_coadded=0
#--pixelList=pixelList.csv 
#--nside=64 --RAmin=0. --RAmax=5.
#--pixelList=pixelList.csv 

obs_coadd=${1:-0}
lc_coadd=${2:-1}
smflux=${3:-0}
season=${4:-3}

python run_scripts/sim_to_fit/run_sim_to_fit.py --dbName baseline_v5.0.0_10yrs --dbDir ../DB_Files --dbExtens npy --OutputSimu_save 1 --OutputSimu_throwafterdump 0 --SN_x1_type random --SN_x1_min -2.0 --SN_color_type random --SN_color_min 0.2 --SN_z_type random --SN_z_min 0.01 --SN_z_max 1.1 --SN_z_step 0.1 --SN_sigmaInt 0.0 --SN_z_rate Hounsell --SN_daymax_type random --Simulator_model salt3 --Simulator_version 2.0 --Fitter_model salt3 --Fitter_version 2.0 --MultiprocessingSimu_nproc 8 --MultiprocessingFit_nproc 8 --nproc_pixels 8 --nproc 1 --SN_NSNfactor 30 --fit_selected 0 --ebvofMW_pixel 0.0 --fieldType DD --nside 128 --Fitter_parnames t0,x1,c,x0 --InstrumentSimu_telescope_tag 1.9 --InstrumentFit_telescope_tag 1.9 --Fitter_sigmaz 1e-05 --lookup_ddf input/simulation/lookup_ddf.csv --saturation_effect 0 --saturation_psf single_gauss --saturation_ccdfullwell 120000.0 --SN_z_sigmaz 1e-05 --fit_remove_sat 0 --SN_NSNabsolute -1 --LCSelection_snrmin 1.0 --code new --SN_minRFphaseQual -10.0 --SN_maxRFphaseQual 35.0 --InstrumentSimu_atmosType const --fit_coadded 0 --Cosmology_w0 -1.0 --Cosmology_wa 0.0 --InstrumentSimu_sigma_airmass 0.0 --InstrumentSimu_sigma_aerosol 0.0 --InstrumentSimu_sigma_pwv 0.0 --InstrumentSimu_sigma_ozone 0.0 --InstrumentSimu_ntrial_zp 1 --Pixelisation_nside 128 --fieldName COSMOS --ProductionIDSimu prod_COSMOS_${season} --Observations_season ${season} --SN_NSNabsolute=-1 --Observations_coadd ${obs_coadd} --LC_coadd=${lc_coadd} --OutputSimu_directory ../newtest_simu_obscoadd_${obs_coadd}_smearf_${smflux}_lccoadd_${lc_coadd} --OutputFit_directory ../newtest_simu_obscoadd_${obs_coadd}_smearf_${smflux}_lccoadd_${lc_coadd}  --SN_smearFlux ${smflux}  --pixelList=pixelList.csv --LC_snrmin=1. --SN_simuFile simuparams_COSMOS.hdf5

#--SN_simuFile SN_simu_params_DDF_test_DB_season_2.hdf5
