zmax: zmax_val
dithering: dithering_val
simuType: simuType_val
outDir: outDir_val
templateDir: templateDir_val
saveData: saveData_val
coadd: coadd_val
nodither: nodither_val
ramin: ramin_val
ramax: ramax_val
decmin: decmin_val
decmax: decmax_val
verbose: verbose_val
ploteffi: ploteffi_val
outputType: outputType_val
T0s: T0s_val
lightOutput: lightOutput_val
proxy_level: proxy_level_val